
services:

  traefik:
    image: "traefik"
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "8880:80"
      - "8443:443"
    volumes:
      - ./traefik_data:/letsencrypt
      - ./docker.sock:/var/run/docker.sock:ro

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "0.0.0.0:8899:8899"
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
    environment:
      - NODE_ENV=production
      # - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      # - WEBHOOK_URL=http://192.168.1.47:5678/
      # - NODES_EXCLUDE=[]
      - N8N_HOST=${DOMAIN_NAME}
      - N8N_PORT=8899
      - N8N_PROTOCOL=https           # ใช้ http เพื่อให้เข้าทาง IP ได้
      - N8N_SECURE_COOKIE=false    
       # ปิดเพื่อให้เข้าผ่าน IP (Non-HTTPS) ได้
      # - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/ # แต่ส่งออก Webhook เป็น HTTPS เสมอ
      - WEBHOOK_URL=http://192.168.1.47:8899/

      - GENERIC_TIMEZONE=Asia/Bangkok
      - TZ=Asia/Bangkok
    # user: "${UID}:${GID}" # หรือใช้ "root" เพื่อตัดปัญหาเรื่องสิทธิ์ (แต่ไม่แนะนำในแง่ความปลอดภัย)
    # sudo chown -R 1000:1000 /home/ubuntu/n8n-deploy/n8n_data
    # sudo chown -R 1000:1000 ./n8n_data
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./local-files:/files

# ในหน้าตั้งค่าของ Cloudflare SSL/TLS settings: 
# ให้เลือกเป็นโหมด "Flexible" (Cloudflare คุยกับ n8n เป็น http แต่คุยกับ User เป็น https)


  minio:
    image: minio/minio:latest
    ports:
      - "7000:9000"
      - "7001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - ./docker_minio:/data
    command: server --address ":9001" --console-address ":9000" /data
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./docker_mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  # API port
      - "6334:6334"  # gRPC (optional)
    environment:
      - QDRANT__SERVICE__API_KEY=passwordapiisxxx  # กำหนดรหัสผ่านที่นี่      
    volumes:
      - ./docker_qdrant_storage:/qdrant/storage
# sudo rm -rf ./docker_mongo
# sudo docker exec -it mongodb /bin/bash
# mongosh -u admin -p password123 --authenticationDatabase admin
# show dbs	            ดูรายชื่อ Database ทั้งหมดที่มี
# use <ชื่อdbs>
# show collections
# db.n8n_chat_histories.countDocuments() เพื่อเช็คว่ามีเอกสาร (Document) อยู่ข้างในบ้างไหม
# db.n8n_chat_histories.findOne() รันคำสั่งนี้เพื่อดูหน้าตาข้อมูล 1 ชุด:


# db.mycollection.insertOne({name: "test"})     ลองเพิ่มข้อมูล (Document) เข้าไปใน Collection
# db.mycollection.find()	                      ดูข้อมูลทั้งหมดใน Collection นั้น